-- Fix the courses_status_check constraint to include all valid CourseStatus enum values
-- The constraint was auto-generated by Hibernate with an older set of values

ALTER TABLE courses DROP CONSTRAINT IF EXISTS courses_status_check;

ALTER TABLE courses ADD CONSTRAINT courses_status_check
    CHECK (status IN ('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'ACTIVE', 'COMPLETED', 'CANCELLED'));
