spring.application.name=MessageApp
server.address=0.0.0.0
server.port=8080
spring.jpa.database=POSTGRESQL
spring.sql.init.platform=postgres
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/messageapp}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123}
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.default_batch_fetch_size=50
jwt.secret=${JWT_SECRET:2Qw1Qk5vQ2p6b3J4bGd2d2h5b2J6d3J4bGd2d2h5b2J6d3J4bGd2d2h5b2J6d3J4bGd2d2h5b2J6d3J4bGd2d2h5b2J6d3J4bGd2d2h5b2J6d3J4bGQ=}

# File upload settings
app.base-url=${APP_BASE_URL:http://46.249.100.239:8080}
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB

# Najva SMS
najva.sms.api-key=${NAJVA_SMS_API_KEY:YOUR_API_KEY_HERE}
najva.sms.sender=90003724
najva.sms.template-name=opt
najva.sms.base-url=https://sms.najva.com/v1
