FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY style.css /usr/share/nginx/html/style.css
COPY app.js /usr/share/nginx/html/app.js
COPY room.html /usr/share/nginx/html/room.html
COPY room.js /usr/share/nginx/html/room.js
COPY room.css /usr/share/nginx/html/room.css
EXPOSE 80
